### ISSUE TITLE
Fix main header component

### ISSUE THREAD

**Issue by artemmatiushenko1** [KhrapkoVasyl/Cooka#2]
- [x] Remove shadow and logo
- [x] Add chip with profile icon and username -> onClick: appears menu with logout option
Smth like that -> ![image](https://user-images.githubusercontent.com/71723893/216386778-6c396bab-e804-40d7-b2f1-68191702576e.png)

**Comment by akaeyuhi** [comment]
Closed in 4ef5753103297d202a00416da22ae78386cbb047
